# Generated by Django 3.2.9 on 2021-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
